# Settings for libraries used by specific LAMMPS packages
# this file is auto-edited when those packages are included/excluded

PKG_INC =   -I../../lib/voronoi/includelink -I../../lib/colvars 
PKG_PATH =  -L../../lib/voronoi/liblink -L../../lib/colvars$(LIBOBJDIR) 
PKG_LIB =   -lvoro++ -lcolvars 

PKG_SYSINC =  $(voronoi_SYSINC) $(colvars_SYSINC) 
PKG_SYSLIB =  $(voronoi_SYSLIB) $(colvars_SYSLIB) 
PKG_SYSPATH = $(voronoi_SYSPATH) $(colvars_SYSPATH) 
